Concordium/concordium-misc-tools

id-verifier/frontend/src/Root.tsx
Browser wallet API was used even though a connection through walletconnect was formed.
- Use provider used to form connection to submit proof request.
=> Use correct provider when connected through walletconnect

id-verifier/frontend/src/wallet-connection.tsx
Aligns how proof rejections are presented across wallets.
- Handle wallet connect error format
=> Handle wallet connect rejection properly

kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml, kpi-tracker/src/main.rs
Adding onto collecting account metrics, this PR adds
- account transactions
- contract modules deployed
- contracts instantiated
=> Collect transaction and contract module/instance metrics

genesis-creator/Cargo.lock, genesis-creator/src/config.rs, genesis-creator/src/genesis.rs, genesis-creator/src/main.rs, id-verifier/Cargo.lock, node-liveness-checker/Cargo.lock, state-compare/Cargo.lock
Bump the Rust SDK after changes in dependencies related to grpc-api.
=> Bump Rust SDK. No functional changes.

kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml, kpi-tracker/resources/schema.sql, kpi-tracker/src/main.rs
Connects to a DB and uses it to store metrics collected from a node. DB connection is managed in a separate thread which the node process communicates with. Furthermore, data is inserted transactionally to allow for easy restoration from the height of the latest recorded block.
Optimisations to make the service production ready are yet to be made
- Changed models with details of entities to not explicitly reference block, as everything is collected per block anyway.
- Removed command line args and code used for data collection debugging
- Removed constraint on unique transaction relations in DB to allow transactions between account aliases of the same account
- [Transaction between aliases of same account](https://dashboard.testnet.concordium.com/lookup/0bf9b0d773c19535cef8434715b4ec066dde …
=> Connect to and use database from service

README.md, kpi-tracker/README.md
This PR adds a readme detailing the steps required to get the project running in a development environment.
=> [KPI-tracker] Add README documentation to project

.github/workflows/ci.yaml, genesis-creator/Cargo.lock, id-verifier/Cargo.lock, node-liveness-checker/Cargo.lock, state-compare/Cargo.lock
Bump the version of the Rust SDK.
=> Bump the SDK version.

genesis-creator/Cargo.lock, genesis-creator/src/genesis.rs, id-verifier/Cargo.lock, id-verifier/src/main.rs, network-dashboard-proxy/Cargo.lock, node-liveness-checker/Cargo.lock, state-compare/Cargo.lock
Propagate version changes from the Rust SDK.
=> Bump concordium-rust-sdk version.

.github/workflows/ci.yaml, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml, genesis-creator/Cargo.lock, genesis-creator/src/main.rs, id-verifier/Cargo.lock, kpi-tracker/Cargo.lock, kpi-tracker/README.md, network-dashboard-proxy/Cargo.lock, network-dashboard-proxy/Cargo.toml, node-liveness-checker/Cargo.lock, recover-id-object/Cargo.lock, recover-id-object/Cargo.toml, recover-id-object/README.md, recover-id-object/src/main.rs, state-compare/Cargo.lock, state-compare/README.md, wallet-proxy-load-simulator/Cargo.lock
Add a tool to do ID recovery and extract identity objects as JSON files.
This is useful when testing ID 2.0 or other ZK proof related functionality.
=> Add a tool to recover ID objects.

genesis-creator/examples/single-baker-example-p5.toml
Add an example of a single baker genesis for p5.
This should go in combination with the tutorial on how to run a local chain.
=> Add an example of a single baker genesis.

wallet-connect-test-bench/front-end/package.json, wallet-connect-test-bench/front-end/src/Main.tsx, wallet-connect-test-bench/front-end/src/WalletConnectorTypeButton.tsx, wallet-connect-test-bench/front-end/src/index.css, wallet-connect-test-bench/front-end/src/index.html
Attempt to improve UI so that it works on smaller screens as well.
Use bootstrap instead of custom CSS for basic grid layout.
=> Play around with styling of the test bench.

genesis-creator/examples/genesis6.toml
Correct the block time comment at the top of the toml file and shrink the timeout factor a bit.
=> Fix comment on block time and timeoutIncrease factor is shrinked a bit.

chain-prometheus-exporter/CHANGELOG.md, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml, generator/CHANGELOG.md, generator/Cargo.lock, generator/Cargo.toml, genesis-creator/CHANGELOG.md, genesis-creator/Cargo.lock, genesis-creator/examples/genesis1.toml, id-verifier/Cargo.lock, id-verifier/Cargo.toml, kpi-tracker/CHANGELOG.md, kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml, network-dashboard-proxy/CHANGELOG.md, network-dashboard-proxy/Cargo.lock, network-dashboard-proxy/Cargo.toml, node-liveness-checker/CHANGELOG.md, node-liveness-checker/Cargo.lock, node-liveness-checker/Cargo.toml, recover-id-object/Cargo.lock, state-compare/CHANGELOG.md, state-compare/Cargo.lock, state-compare/Cargo.toml, state-compare/README.md, state-compare/src/main.rs
Update tools for protocol version 6 and node version 6.
Addresses #75 
=> Update services for protocol 6.

wallet-connect-test-bench/front-end/CHANGELOG.md, wallet-connect-test-bench/front-end/package.json, wallet-connect-test-bench/front-end/src/Main.tsx, wallet-connect-test-bench/front-end/src/writing_to_blockchain.ts
- Add max energy field
This is for testing/confirming the following fix:
https://concordium.atlassian.net/browse/CBW-747
=> Add max energy field

kpi-tracker/CHANGELOG.md, kpi-tracker/grafana/dashboard.json, kpi-tracker/resources/schema.sql
Addresses #89 and #90.
The information was already in the database, so--aside from an added function in `schema.sql`--only Grafana changes were needed.
=> Transaction by type + #accounts with CCD transfers

kpi-tracker/CHANGELOG.md, kpi-tracker/grafana/dashboard.json, kpi-tracker/resources/schema.sql, kpi-tracker/src/main.rs
Addresses #94.
When counting bakers, we now also check if a baker is a finalizer and keep track of the finalizer count separately.
=> [KPI Tracker] Add active finalizers graph

id-verifier/frontend/package.json
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Describe the changes that were needed.
_Remove if not applicable.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
=> Fix build error by correcting package.json

kpi-tracker/grafana/dashboard.json
Fix description of the minted CCD panel.
=> Fix description of the Minted CCD panel.

.github/workflows/ci.yaml, chain-prometheus-exporter/Cargo.lock, generator/Cargo.lock, genesis-creator/Cargo.lock, id-verifier/Cargo.lock, kpi-tracker/Cargo.lock, network-dashboard-proxy/Cargo.lock, recover-id-object/Cargo.lock, state-compare/Cargo.lock
Bump Rust SDK after removing V1 API.
=> Update lock files

.github/workflows/ci.yaml, .github/workflows/release.yml, chain-prometheus-exporter/CHANGELOG.md, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml, chain-prometheus-exporter/src/main.rs, company-id-gui/src-tauri/Cargo.lock, company-id-gui/src-tauri/Cargo.toml, generator/Cargo.lock, generator/Cargo.toml, generator/src/generator.rs, genesis-creator/Cargo.lock, genesis-creator/Cargo.toml, genesis-creator/src/lib.rs, id-verifier/Cargo.lock, id-verifier/Cargo.toml, kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml, kpi-tracker/src/main.rs, recover-id-object/Cargo.lock, recover-id-object/Cargo.toml, state-compare/Cargo.lock, state-compare/Cargo.toml, wallet-proxy-load-simulator/Cargo.lock
=> Bump SDK version in services.

.github/workflows/ci.yaml
Using a single matrix as a single point of truth instead of replicating
Only run the jobs which has been altered based on pathing criteria. This is especially important since I am about to introduce testing and that takes significant more time, and if the corresponding package has not even been updated then why run the tests?
Updated ci.yaml
=> Single matrix

chain-prometheus-exporter/CHANGELOG.md, generator/CHANGELOG.md, genesis-creator/CHANGELOG.md, genesis-creator/src/config.rs, kpi-tracker/CHANGELOG.md, kpi-tracker/src/main.rs, recover-id-object/CHANGELOG.md, state-compare/CHANGELOG.md
Updates the Rust SDK submodule to support the protocol 7 changes.
=> Update Rust SDK

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/bin/service.rs
We are consistently using environment variable to parse args. This PR strives to be consistent with such practice
endpoint arg as environment variable
=> Backend as an env variable

.github/workflows/ci.yaml, .github/workflows/release-recover-id-object.yml, kpi-tracker/scripts/Dockerfile
Bump rust version for consistency
=> Bump rust version

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/bin/api.rs
Fixing severity. If a user sends invalid content we should by no means receive a severity of error
=> Fix log messages

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/google_cloud.rs, notification-server/src/models.rs, notification-server/src/processor.rs
We need to add type to the notification
Type to notification
Use serde to serialise to serialise object
Change amount to String
=> Type to notification

notification-server/src/bin/service.rs, notification-server/src/database.rs, notification-server/src/models.rs, notification-server/src/processor.rs
Using preferences when listening on transactions
Read preferences up from database
Filter corresponding type out if not included in preferences
=> Preferences

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/bin/service.rs
Given connection issues, we should retry
Gracefully handle errors when stream provides error
Always loop
=> Restart client

generator/CHANGELOG.md, generator/Cargo.lock, generator/Cargo.toml, generator/README.md, generator/src/generator.rs, generator/src/main.rs
Update the transaction generator to support generating register data transactions.
- Add a `register-data` transaction generator mode.
=> Generate register data transactions.

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/google_cloud.rs, notification-server/src/models/notification.rs
Remove init_ from the serialized value.
=> Init prefix

notification-server/Cargo.lock, notification-server/Cargo.toml
=> Updated version

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/google_cloud.rs
We need to notify able that we have content to be read and do not want to use their standard templates
Adding content available
Docs: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message
=> Content available flag

.github/workflows/release-chain-prometheus-exporter.yml
Jenkins is broken and we want to migrate the release flows
Add release flow for chain-prometheus-exporter
=> Chain prometheus exporter release flow

chain-prometheus-exporter/CHANGELOG.md, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml
Just a small version bump to retry the release flow through GitHub actions rather than jenkins.
=> Bump version to retry release

.github/workflows/release-chain-prometheus-exporter.yml
=> Fix dockerfile name

chain-prometheus-exporter/CHANGELOG.md, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml
Attempt 2 of https://github.com/Concordium/concordium-misc-tools/pull/214
=> Bump version attempt 2

chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml, chain-prometheus-exporter/scripts/build.Dockerfile
Fix issues with release pipeline
Bump version
=> Chain prometheus explorer release

.github/workflows/release-kpi-tracker.yml, chain-prometheus-exporter/CHANGELOG.md, kpi-tracker/CHANGELOG.md, kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml
Add manual run step
Add manual run
Reuse environment variable across the entire file
=> Bumped kpi tracker

.github/workflows/release-kpi-tracker.yml, kpi-tracker/CHANGELOG.md, kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml
Fix kpi tracker release script
Bumping kpi tracker version
=> Bump kpi tracker

.github/workflows/release-chain-prometheus-exporter.yml, .github/workflows/release-kpi-tracker.yml, .github/workflows/release-notification-server.yml, .github/workflows/release-recover-id-object.yml, .github/workflows/release-wallet-test-bench.yml, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml
Update to be using unprivileged user
Update and add more meaningful name for unprivileged user environment
Bump one service to test that the username password combination is correct.
=> Update to be using unprivileged user

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/google_cloud.rs
Not working in background
Remove apns config
=> Revert apns

notification-server/CHANGELOG.md, notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/bin/service.rs
I want to be able to trace whether the notification service is still successfully processing blocks
=> Ensure we can get latest timestamp

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/bin/service.rs, notification-server/src/database.rs
https://linear.app/concordium/issue/MIS-91/removal-of-unregistered-device-token
Removal of subscription from the database
=> Removal of devices

kpi-tracker/CHANGELOG.md, kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml
- Prepare new release for `KPI` tracker.
=> Update KPI tracker

Cargo.lock, kpi-tracker/CHANGELOG.md, kpi-tracker/Cargo.toml
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Describe the changes that were needed.
_Remove if not applicable.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
=> Bump version of kpi tracker for deployment
