node-liveness-checker/scripts/Dockerfile
The Jenkins build needs to have protoc installed to build the node-liveness-checker.
Added protoc installation to the node-liveness-checker builder image.
=> Install protoc in the node-liveness-checker build image

id-verifier/frontend/.eslintignore, id-verifier/frontend/.eslintrc.js, id-verifier/frontend/.prettierrc, id-verifier/frontend/package.json, id-verifier/frontend/src/Root.tsx, id-verifier/frontend/src/wallet-connection.tsx, id-verifier/frontend/yarn.lock
Add walletconnect integration to the proof explorer application.
- Added two buttons to give the user the option to choose which wallet to connect the application to.
- Created a common abstraction to handle wallet connection.
Currently, the mobile wallet does not support generating proofs, so this can't be tested fully, and the proof request to wallet connect is based on the payload used internally in the browser wallet.
The way this can be tested is
- A connection can be created to a mobile wallet
- Proofs can still be created through the browser wallet
- It is possible to change wallet and disconnect from either wallet
=> Proof explorer walletconnect

kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml, kpi-tracker/src/main.rs
The purpose here is to mimic the database implementation of this, which will be two tables:
- Relations between accounts and transactions (unique "address/transaction hash" pairs)
- Relations between contracts and transactions (unique "contract address/transaction hash" pairs)
Should be reviewed subsequently to #24.
- Canonicalize accounts to avoid account aliases
- Add `HashSet`s to store transaction relations 
=> Add tables recording affected contracts/accounts for each transactions

kpi-tracker/src/main.rs
Records total amount staked across all pools for payday blocks. Right now this is stored as an `Option`, where non-payday blocks will have `None`. I don't know if this is a good solution or not, but for now it's the simplest way to implement this behaviour.
Dependent on #25 
- Record total stake for payday blocks
- Add option to specify which block (height) to start from as a command line argument
=> Record total stake for payday blocks (which also implies blocks must be > protocol version 4)

chain-prometheus-exporter/CHANGELOG.md, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml, chain-prometheus-exporter/src/main.rs
According to the docs it states that: _CHAIN_PROMETHEUS_EXPORTER_ACCOUNTS the comma-separated list of strings in the form label:address where label is a valid prometheus label, and address is an account address._
Entering the following prior to change: 
```
❯ cargo run -- --account 'some_account_1:3qEzbyRuTo3CgWv6wCmyuhDiKzcNwWzRxaAjfEktw9rbPGtL1w,some_account_2:39oMXkk3Fjb3tMRNfvnnFxJZPF8ATmBdajyBv9gk7iSRMtZNqV'
Compiling chain-prometheus-exporter v1.0.0 (/Users/lassemolleralm/Documents/Projects/concordium-misc-tools/chain-prometheus-exporter)
Finished dev [unoptimized + debuginfo] target(s) in 2.24s
Running `target/debug/chain-prometheus-exporter --account 'some_account_1:3qEzbyRuTo3CgWv6wCmyuhDiKzcNwWzRxaAjfEktw9rbPGtL1w,some_account_2:39oMXkk3Fjb3tMRNfvnnFxJZPF8ATmBdajyBv9gk7iSRMtZNqV' …
```
=> Add value_delimiter param

wallet-connect-test-bench/front-end/CHANGELOG.md, wallet-connect-test-bench/front-end/package.json, wallet-connect-test-bench/front-end/src/Main.tsx, wallet-connect-test-bench/front-end/src/WalletConnectorTypeButton.tsx
The hosted `test bench` front end is now added to the `developer dApp example` section. Since an external person can now try it out (and not only our internal testing people), the switch should be improved at the front end to make it clear which option is selected. The selected option at a switch is now in bold font.
- Change: Selected switch option is displayed in bold font now
=> Change that selected switch option is in bold font

wallet-connect-test-bench/front-end/CHANGELOG.md, wallet-connect-test-bench/front-end/package.json, wallet-connect-test-bench/front-end/src/Main.tsx
All hosted front ends should have a way to find the source code easily. Either through a link to an associated tutorial (that contains links to the source code) or if no tutorial exists through a link to the source code.
Add link to source code.
=> Add link to source code

wallet-connect-test-bench/front-end/CHANGELOG.md, wallet-connect-test-bench/front-end/package.json, wallet-connect-test-bench/front-end/src/Main.tsx, wallet-connect-test-bench/front-end/src/Root.tsx, wallet-connect-test-bench/front-end/src/constants.ts, wallet-connect-test-bench/front-end/src/reading_from_blockchain.ts, wallet-connect-test-bench/front-end/yarn.lock
JSON-RPC is deprecated and will be eventually removed from all our libraries. This PR migrates the wallet test bench dApp.
- Replace using jsonRPC with gRPC
=> Change jsonRPC to gRPC in walletTestBench

kpi-tracker/CHANGELOG.md, kpi-tracker/grafana/dashboard.json, kpi-tracker/resources/schema.sql, kpi-tracker/src/main.rs
Addresses #96, #97, #99, #100, and #101.
- The graph for active bakers is now "Active staking accounts" and shows bakers and delegators stacked.
- The staked CCD graph has been split into baker equity, actively delegated, and passively delegated.
- A new graph that shows the status of active bakers (i.e. open, closed, closed for new).
- A new graph that plots the number of bakers being delegated to.
To accomplish this, quite a few column were added to the `paydays` table.
=> [KPI Tracker] Delegation-related graphs

company-id-gui/package.json, company-id-gui/src-tauri/Cargo.lock, company-id-gui/src-tauri/Cargo.toml, company-id-gui/src-tauri/src/main.rs
If the user changes the name of any of the saved files Windows will remove the JSON file extension. This PR fixes this.
Adding a "file extension filter" fixes the issue.
=> Fix save file extension on Windows

company-id-gui/package.json, company-id-gui/src-tauri/Cargo.lock, company-id-gui/src-tauri/Cargo.toml, company-id-gui/src-tauri/src/main.rs
The error message when selected network and node URL do not match prints the net code of the network instead of the name of the network. This PR fixes this.
=> Fix wrong network error message

generator/CHANGELOG.md, generator/Cargo.lock, generator/Cargo.toml, generator/README.md, generator/src/generator.rs
Addresses #107.
The initial minting of wCCD is moved from the instantiation to the generator.
=> Stop wCCD generator minting for everyone too fast

company-id-gui/README.md
Brush out how to sign the company id tool for mac
Updated the readme
_Remove if not applicable.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
=> Updated documentation for the company-id gui

recover-id-object/scripts/Dockerfile
As part of the reporting in https://docs.google.com/document/d/1CxI5-c0bRdJm0C0THE18xh4DoTOLPRNn0Su2qWZMCrM we need to report an issue given a non successful recovery occurs. The output channel here is slack, and they use callbacks. Hence we need to use a callback which I would like to use curl for. 
Install curl to dockerimage 
=> Curl to recover-id-object

.github/workflows/ci.yaml, .github/workflows/release-notification-server.yml
I need a different rust version on the notification-server. I do not want to update all. Also logically it makes sense that we do not have to big bang bump all rust versions when we do that. 
ci.yaml adding a map which takes different rust versions than default
=> Individual rust versions

state-compare/CHANGELOG.md, state-compare/Cargo.lock, state-compare/Cargo.toml, state-compare/README.md, state-compare/src/main.rs
Previously this tool tried to take protocol versions into account and account for migration changes, to ensure that migrations are done correctly. However, doing this essentially involves re-implementing the migration changes every time a new protocol version is released. So we opt instead to merely print a diff of the changes between states. The user must then manually inspect the changes and decide for themselves whether they are expected or not.
The tool has largely the same function structure as before but does not carry around a boolean any more to indicate if a difference was found. Differences are instead printed with color to indicate the changes.
=> Change state compare to only output a diff

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/google_cloud.rs, notification-server/src/models/notification.rs, notification-server/src/processor.rs
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message
Data only allows for String and String.
This means we need to take ownership of some of the types
Changed serialisation for those fields which did not return a string
=> Fix gcp format

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/Makefile, notification-server/README.md, notification-server/src/bin/api.rs, notification-server/src/bin/service.rs
Align prometheus env name
Rename env variable
=> Align env variables

chain-prometheus-exporter/CHANGELOG.md, chain-prometheus-exporter/Cargo.lock, chain-prometheus-exporter/Cargo.toml, chain-prometheus-exporter/src/main.rs, generator/Cargo.lock, generator/src/generator.rs, genesis-creator/CHANGELOG.md, genesis-creator/Cargo.lock, genesis-creator/Cargo.toml, genesis-creator/src/lib.rs, id-verifier/CHANGELOG.md, id-verifier/Cargo.lock, id-verifier/Cargo.toml, kpi-tracker/CHANGELOG.md, kpi-tracker/Cargo.lock, kpi-tracker/Cargo.toml, notification-server/CHANGELOG.md, notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/database.rs, notification-server/src/google_cloud.rs, notification-server/src/processor.rs, recover-id-object/CHANGELOG.md, recover-id-object/Cargo.lock, recover-id-object/Cargo.toml, state-compare/CHANGELOG.md, state-compare/Cargo.lock, state-compare/Cargo.toml
Bumps all the tool versions to release the versions that support protocol 7.
* Updated the Rust SDK to the 5.0.0 release.
* Got rid of various minor warnings.
* Bumped version of almost all the tools (I did not include the generator as that seems to have a protocol-7-supporting release already).
=> Update all tool versions to support protocol 7

notification-server/CHANGELOG.md, notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/scripts/Dockerfile, notification-server/src/bin/api.rs, notification-server/src/bin/service.rs, notification-server/src/database.rs
Global prepared statement are causing issues when using them from another thread. 
Always reinitialise prepared statements, but use cache to ensure to lower overhead.
Bump psql to version 14 because would only initialise version 11 as is. This might give issues.
=> Prepared statements issue

notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/src/bin/service.rs
Adding threshold to when a notification is no longer considered valid enough to be sent
Single function which ensures catchup at start time
=> Notification ttl

.github/workflows/release-notification-server.yml, notification-server/CHANGELOG.md, notification-server/Cargo.lock, notification-server/Cargo.toml, notification-server/scripts/Dockerfile
Pipeline release flow fails. 
As part of the installation I am doing:
http://apt.postgresql.org/pub/repos/apt/dists/
Which for some reason after the release during the weekend no longer contains a buster release. Since we are anyways using bookworm elsewhere this is the reason for such change
=> Fix pipeline fails

notification-server/README.md, notification-server/test-device/firebase-messaging-sw.js, notification-server/test-device/index.html
Notification server readme is missing some details in how to get it up and running and provide no easy way to test the result.
This PR extends the readme and adds a small rough webapp to simulate the device to test notifications locally.
=> Update readme and implement simple test device for notifications

Cargo.lock, notification-server/CHANGELOG.md, notification-server/Cargo.toml, notification-server/README.md, notification-server/src/database.rs, notification-server/src/google_cloud.rs, notification-server/src/models/device.rs, notification-server/src/models/notification.rs, notification-server/src/processor.rs, notification-server/test-device/index.html
Extend notifications for receiving PLT tokens, when the relevant preference is set.
[Task](https://linear.app/concordium/issue/COR-1697/update-notification-service-to-send-plt-notifications).
Builds on top of the minor refactor PR: https://github.com/Concordium/concordium-misc-tools/pull/252
- Introduce a new preference "plt-tx"
- Introduce a new notification type.
=> Extend notifications for receiving PLT tokens
